### ISSUE TITLE
jetpack requires RHEL7.8 on ansible jumphost, docs don't say that

### ISSUE THREAD

**Issue by bengland2** [redhat-performance/jetpack#316] opened 2020-12-07 14:49 UTC
Is RHEL7 the preferred ansible jumphost OS distro?  or RHEL8?  It doesn't say [here in docs](https://jetpack-docs.readthedocs.io/en/latest/requirements.html).   RHEL7 seems to cause problems, see[ this log for details](http://perf1.perf.lab.eng.bos.redhat.com/pub/bengland/tmp/jetpack/jetpack.2020-12-07-14-26.log).

**Comment by asyedham** [comment] 2020-12-07 15:27
It should work on both. I usually use RHEL 7 jump host. Can you share the RHEL 7 version on which you are facing this problem as I tried reproducing it on an RHEL 7.8 jump host but didn't encounter the above issue http://paste.openstack.org/show/800800/

**Comment by bengland2** [comment] 2020-12-07 15:31
[This procedure](https://docs.google.com/document/d/1Ma1Hn4SSTljGdg2UoY-lZzHfCRjwGh8QzECDVRYsWiY/edit) is how I prepare my cluster to run jetpack.

The python3-virtualenv package is not installing.  Can't figure out how it ever would.
```
ok: [localhost] => (item=python3-virtualenv) => {                                                                                                          [622/1903]
    "ansible_loop_var": "item", 
    "changed": false, 
    "changes": {
        "installed": [
            "python3-virtualenv"
        ]
    }, 
    "failed_when_result": false, 
    "item": "python3-virtualenv", 
    "rc": 1, 
    "results": [
        ""
    ]
}

MSG:

Traceback (most recent call last):
  File "/usr/bin/yum", line 4, in <module>
    import yum
ModuleNotFoundError: No module named 'yum'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/yum", line 6, in <module>
    print >> sys.stderr, """\
TypeError: unsupported operand type(s) for >>: 'builtin_function_or_method' and '_io.TextIOWrapper'. Did you mean "print(<message>, file=<output_stream>)"?

ok: [localhost] => (item=python3-libselinux) => {
    "ansible_loop_var": "item", 
    "changed": false, 
    "failed_when_result": false, 
    "item": "python3-libselinux", 
    "rc": 126, 
    "results": [
        "No package matching 'python3-libselinux' found available, installed or updated"
    ]
}

MSG:

No package matching 'python3-libselinux' found available, installed or updated
```

**Comment by bengland2** [comment] 2020-12-07 15:33
will try switching ansible jumphost to RHEL8 and see if problem goes away

**Comment by asyedham** [comment] 2020-12-07 15:34
are you using RHEL 7.7?

**Comment by bengland2** [comment] 2020-12-07 15:36
yes, that's what default Alias lab deployment gave me

**Comment by bengland2** [comment] 2020-12-07 15:38
Am upgrading to RHEL7.8 and seeing if problem goes away first

**Comment by asyedham** [comment] 2020-12-07 15:39
So with RHEL 7.7, we don't have support for python3 packages. So instead, please use RHEL 7.8

**Comment by bengland2** [comment] 2020-12-07 15:57
It's getting much farther now, so I think this was the problem.  Would help if docs were updated to mention you need > RHEL7.7

**Comment by asyedham** [comment] 2020-12-07 16:13
@bengland2 Thanks for reporting the issue. We have updated the docs #317  and since the issue is not reproducing in RHEL 7.8. Closing the issue.

**Closed as completed by asyedham** 2020-12-07 16:13 UTC
